/*
 * generated by Xtext 2.27.0
 */
package org.example.entities.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class EntitiesProposalProvider extends AbstractEntitiesProposalProvider {
}
